config/routes.rb
Rails.application.routes.draw do

  root 'users#index'

  resources :users, only: [:create]

  get 'update_users', to: 'users#update_users'

  post 'delete_user', to: 'users#delete_user'

  post 'destroy_user', to: 'users#destroy_user'

  get 'new_token', to: 'users#new_token'

  post 'new_token', to: 'users#send_token'
end

app/models/user.rb
class User < ActiveRecord::Base

  validates_presence_of :name, :email, :github_username
  validates_uniqueness_of :github_username
  default_scope { order('contributions DESC')}

  require 'net/http'

  def github_contributions
    doc = Nokogiri::HTML(open("https://github.com/#{self.github_username}"))
    contributions = doc.css("span.contrib-number")[0].text.remove!(" total")
    contributions.remove!(",")
    contributions.to_i
  end

  def github_streak
    doc = Nokogiri::HTML(open("https://github.com/#{self.github_username}"))
    streak = doc.css("span.contrib-number")[1].text.remove!(" days")
    streak.to_i
  end

  def github_user?
    uri = URI("https://github.com/#{self.github_username}/")
    response = Net::HTTP.get_response(uri)
    response.code == '404' ? false : true
  end

  def update_user_info
    self.contributions = github_contributions
    self.streak = github_streak
    self.secret = generate_delete_secret
    self.save
  end

  def generate_delete_secret
    self.secret = Faker::Internet.password
  end

  #class methods here down

  def self.update_github_info_for_all
    users = User.all
    users.each do |user|
      user.update_user_info
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ui_controller.rb
class UiController < ApplicationController

  def index
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def create
    @user = User.new(user_params)
    @users = User.all

    if @user.github_user?
      if @user.save
        @user.update_user_info
        AppMailer.send_secret_token(@user.id).deliver
        flash[:success] = "Success! Your secret token is: #{@user.secret}"
        redirect_to root_path
      else
        flash[:error] = "Must include name, GitHub username and email address."
        render :index
      end
    else
      flash[:error] = "That GitHub user doesn't exist"
      render :index
    end
  end

  def update_users
    User.update_github_info_for_all
    @users = User.all
    flash[:info] = "Leaderboard Updated!"
    render :index
  end

  def delete_user
    @user = User.find(params[:user_id])
  end


  def destroy_user
    @user = User.find(params[:user_id])

    if @user.secret == params[:secret_token]
      @user.delete
      flash[:success] = "#{@user.github_username} deleted from leaderboard"
      redirect_to root_path
    else
      flash[:error] = "That is not the correct secret code for #{@user.github_username}"
      render :delete_user
    end

  end

  #actions to resend the user secret token

  def new_token
  end

  def send_token
    @user = User.find_by(github_username: params[:github_name])
    if @user
      AppMailer.send_secret_token(@user.id).deliver
      flash[:success] = "We just sent an email to #{@user.email}."
    else
      flash[:error] = "Unable to find #{params[:github_name]} in our database."
    end
    render :new_token
  end

  #end secret token methods

  private

  def user_params
    params.require(:user).permit(:name, :github_username, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper


end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en-US")
  %head
    %title CHANGE IN LAYOUTS/APPLICATION
    %meta(charset="UTF-8")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    = csrf_meta_tag
    = javascript_include_tag "vendor/modernizr"
    = stylesheet_link_tag "application"
    %link(href='http://fonts.googleapis.com/css?family=Raleway:400,200,700' rel='stylesheet' type='text/css')
  %body
    %header
      = render 'shared/header'
    %section.content.clearfix
      /= render 'shared/messages'
      = yield
    %footer
      = render 'shared/footer'
    = javascript_include_tag "application"

app/views/shared/_footer.html.haml
.homepage-footer
  .row.homepage-row
    .small-12.column
      %span.logo-last-word
        =link_to "CHANGE IN FOOTER PARTIAL", root_path, class: 'white-logo'

app/views/shared/_header.html.haml
.contain-to-grid
  .row.show-for-medium-down.bottom-border.centered
    .small-12.columns
      %span.logo-last-word
        =link_to "CHANGE IN HEADER PARTIAL", root_path, class: 'white-logo'
  %nav.top-bar.collapse.show-for-large-up.centered(role="navigation")
    %ul.title-area
      %li.name
        =link_to "" do
          %span.logo-last-word
            =link_to "CHANGE IN HEADER PARTIAL", root_path, class: 'white-logo'

app/views/shared/_messages.html.haml
.message-holder.centered
  - flash.each do |name, msg|
    %div(data-alert=true class="alert-box #{name} radius")
      %a.close(href="#")
        &times;
      = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/ui/index.html.haml
.section
  .row
    .small-12.columns
      %p
        Becoming a programmer takes a small bit of intelligence and a LOT of persistence. Writing code every single day
        keeps your brain focused and helps you grasp difficult concepts.
      %p
        Long form programming is the most beneficial. Having one 2-hour programming session is infinitely better than 4 30-minute sessions. Much like a Heroku dyno, it takes your brain time "spin up" and "load the code". It might take 15 minutes to get the zone, and by that time, if you're doing a 30-minute session, you only have 15 minutes remaining. If you're doing a 2-hour session, you still have 1:45 of great productivity ahead of you.
      %p
        In order to encourage consistent coding, I've build a leaderboard for TeaLeaf Academy. Input your name and
        GitHub username and you'll be added to the leaderboard below. The more you commit, the higher up the leaderboard you'll get!
      %p
        The leaderboard was built using
        =link_to "Foundation Zurb", "http://foundation.zurb.com/"
        a scraper gem called Nokogiri. It's the same gem that powers Capybara's functional testing. If you're curious about the code, take a look here:
        =link_to "Tealeaf Leaderboard GitHub", "https://github.com/pmichaeljones/leaderboard/"
  %hr
    .row
    .small-12.columns.centered
      %p
        This site was built using TDD best-practices by TeaLeaf Academy student
        =link_to "Patrick Jones", "http://pmichaeljones.herokuapp.com"
  %hr
  .row
    .small-12.columns
      %form{"data-abide" => true}
        %fieldset
          %legend Leaderboard Submission Form
          .row
            .small-12.large-4.column
              %label
                Name
                %input(type="text" placeholder="Your Name" class='radius' required=true)
                %small.error Put your name please!
            .small-12.large-4.column
              %label
                GitHub Username
                %input(type="text" id="ghusername" placeholder="GitHub Username" class='radius' required=true)
            .small-12.large-4.column
              %label
                GitHub Username Confirmation
                %input(type="text" placeholder="GitHub Username" class='radius' required=true data-equalto="ghusername")
                %small.error Usernames must match
          .small-12.column.centered
            = submit_tag "Join the Leaderboard!", class: 'button login-button'
            = submit_tag "Refresh Leaderboard!", class: 'button login-button light-blue'
  .row
    .small-12.columns
      %table
        %thead
          %tr
            %th Name
            %th GitHub Username
            %th Yearly Contributions
            %th Current Streak
        %tbody
          %tr
            %td Patrick Jones
            %td pmichaeljones
            %td 744 Total
            %td 20 Days

app/views/users/delete_user.html.haml
.section
  .row
    .small-12.columns
    %hr
      = render 'shared/messages'
  .row
    .small-12.columns
      =form_tag("/destroy_user", method: :post) do
        %fieldset
          %legend Leaderboard Erase Form
          .row.centered
            .small-12.large-6.columns
              =label_tag "Please Enter User Secret Token for: #{@user.github_username}"
              =text_field_tag :secret_token, nil, class: 'radius'
              =hidden_field_tag :user_id, "#{@user.id}"
            .small-12.large-6.columns
              =submit_tag "Erase User from Leaderboard", class: 'button login-button down-a-bit'
          .div.centered
            =link_to "Forgot Token?", new_token_path




  /    =form_tag #controller: 'users', action: 'destroy_user' method: :post do |f|
  /       %fieldset
  /         %legend Leaderboard Erase Form
  /         .row
  /           .small-12.large-3.column
  /             = label_tag "Please enter secret password for user"
  /             = text_field_tag
  /       = submit_tag "Erase User from Leaderboard", class: 'login-button'

app/views/users/index.html.haml
.section
  .row
    .small-12.columns
      %p
        PARAGRAPH 1
      %p
        PARAGRAPH 2
      %p
        PARAGRAPH 3
      %p
        PARAGRAPH 4
  %hr
    .row
    .small-12.columns.centered
      %p
        This site was built using TDD best-practices by TeaLeaf Academy student
        =link_to "Patrick Jones", "http://pmichaeljones.herokuapp.com"
  %hr
  = render 'shared/messages'
  .row
    .small-12.columns
      =form_for(User.new, data: {abide:''}) do |f|
        %fieldset
          %legend Leaderboard Submission Form
          .row
            .small-12.column
              %p Note: You will receive an email containing a secret token. Use that token to remove yourself from the leaderboard.
              %p After adding yourself to the leaderboard, your secret token will also appear in the green "success" box above.
            .small-12.large-3.column
              = f.label :name, "Your Name"
              = f.text_field :name, placeholder: 'Your Name', required: ''
              %small.error Please enter name
            .small-12.large-3.column
              = f.label :github_username, "GitHub Username"
              = f.text_field :github_username, placeholder: 'Your GitHub Username', class: 'radius', required: ''
              %small.error Enter username please!
            .small-12.large-3.column
              = f.label :email, "Email Address"
              = f.text_field :email, placeholder: 'Email Address', class: 'radius', id: "email", type: 'email', required: ''
              %small.error Must be valid email
            .small-12.large-3.column
              %label Email Confirmation
              %input(type="email" placeholder="Email confirmation" class='radius' data-equalto="email" required=true)
              %small.error Emails don't match
          .small-12.column.centered
            = f.submit "Join the Leaderboard!", class: 'button login-button'
            = link_to "Refresh Leaderboard!", update_users_path, class: 'button login-button light-blue'
  .row
    .small-12.columns.centered
      %h2
        Tealeaf Academy Leaderboard
  .row
    .small-12.columns
      %table
        %thead
          %tr
            %th Rank
            %th Name
            %th GitHub Username
            %th Yearly Contributions
            %th Longest Streak
            %th.centered Delete
        %tbody
          -@users.each_with_index do |user, index|
            %tr
              %td #{index + 1}
              %td #{user.name}
              %td=link_to "#{user.github_username}", "https://github.com/#{user.github_username}"
              %td #{user.contributions} Commits
              %td #{user.streak} Days
              %td.centered
                =form_tag("/delete_user", method: :post) do
                  =hidden_field_tag :user_id, user.id
                  =submit_tag "X", class: 'erase-user-button'

app/views/users/new_token.html.haml
.section
  .row
    .small-12.columns
    %hr
      = render 'shared/messages'
  .row
    .small-12.columns
      %p Enter GitHub Username. If we have that username in our database, we will send the secret token to their email on file.
      =form_tag("/new_token", method: :post) do
        %fieldset
          %legend Get New Token Form
          .row.centered
            .small-12.large-6.columns
              =label_tag "GitHub Username"
              =text_field_tag :github_name, nil, class: 'radius'
            .small-12.large-6.columns
              =submit_tag "Get Password Token", class: 'button login-button down-a-bit'